import React from 'react'

const SimplePage = () => {

  return (
    <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Faucibus a pellentesque sit amet porttitor eget dolor morbi. Et netus et malesuada fames ac turpis egestas sed. Est lorem ipsum dolor sit. Duis at tellus at urna condimentum mattis pellentesque. Egestas erat imperdiet sed euismod nisi porta lorem. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Felis eget nunc lobortis mattis aliquam faucibus purus. Arcu dui vivamus arcu felis bibendum ut.

    Praesent semper feugiat nibh sed pulvinar proin. Sed id semper risus in. Cursus in hac habitasse platea dictumst quisque sagittis purus. Dictum non consectetur a erat. Leo duis ut diam quam nulla porttitor massa. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Iaculis urna id volutpat lacus laoreet non. Arcu cursus vitae congue mauris. Est placerat in egestas erat imperdiet sed euismod nisi. Nibh tellus molestie nunc non blandit massa enim nec. Eu mi bibendum neque egestas congue. Nunc id cursus metus aliquam eleifend mi in nulla posuere.
    
    Venenatis tellus in metus vulputate eu scelerisque felis. Sagittis eu volutpat odio facilisis mauris. Sed blandit libero volutpat sed cras ornare arcu dui vivamus. Sed viverra tellus in hac habitasse. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Est ullamcorper eget nulla facilisi etiam dignissim diam quis. Quam nulla porttitor massa id. Faucibus in ornare quam viverra orci sagittis. Ac turpis egestas maecenas pharetra. Arcu bibendum at varius vel. Nisl condimentum id venenatis a condimentum vitae sapien. Sit amet aliquam id diam maecenas. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere ac. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Auctor augue mauris augue neque gravida in. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Ac turpis egestas sed tempus. Bibendum enim facilisis gravida neque convallis a cras. Viverra vitae congue eu consequat ac felis.
    
    In hendrerit gravida rutrum quisque non tellus orci ac. Ac turpis egestas maecenas pharetra convallis posuere morbi leo. Aliquam eleifend mi in nulla posuere sollicitudin aliquam. Aenean euismod elementum nisi quis. Consequat id porta nibh venenatis cras. Lectus magna fringilla urna porttitor rhoncus. Sed egestas egestas fringilla phasellus faucibus. Ac turpis egestas sed tempus urna et. Ultricies mi eget mauris pharetra et ultrices neque ornare. Facilisi morbi tempus iaculis urna id volutpat lacus. Quis ipsum suspendisse ultrices gravida dictum fusce. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique.
    
    Odio ut sem nulla pharetra diam. Elementum integer enim neque volutpat. Sit amet nisl purus in mollis nunc sed id semper. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Vitae congue eu consequat ac felis. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Enim facilisis gravida neque convallis a cras. Tincidunt arcu non sodales neque sodales ut etiam sit amet. Diam volutpat commodo sed egestas egestas fringilla. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Tincidunt id aliquet risus feugiat in ante metus.</div>
  )
}

export default SimplePage